universe = docker
docker_image = pcswanson/suprwtr:v1

transfer_input_files = backup/super_config.yaml,backup/download_list.py,backup/simple_cluster_non_matching_repid_gt_3.txt

pdb=cap_005
log = output/condor_logs/super_w_$(pdb)_$(Cluster)_$(Process).log
error = output/condor_logs/super_w_$(pdb)_$(Cluster)_$(Process).err
output = output/condor_logs/super_w_$(pdb)_$(Cluster)_$(Process).out

executable = runfiles/run_gt_3.sh

should_transfer_files = YES
when_to_transfer_output = ON_EXIT_OR_EVICT

transfer_output_files = ./

+WantGPULab = true

environment = "CLUSTER=$(Cluster) PROCESS=$(Process) RUNNINGON=$$(Name) PDB=$(pdb)"

require_gpus = (Capability == 8.90)
+GPUJobLength = "medium"
request_gpus = 1
request_cpus = 4
request_memory = 16GB
request_disk = 48GB

queue
